# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Spelling"

on:
  push:
    branches:
      - "master"
  pull_request: null
  # Add [skip ci] to commit message to skip CI.

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  spelling:
    name: "Spelling"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Cache pip"
        uses: "actions/cache@v3"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-codespell"

      - name: "Install codespell"
        run: |
          pip install --user 'codespell>=2.2'

      - name: "Search for misspellings"
        run: |
          "$(python -m site --user-base)/bin/codespell"
